V2 geolocation.component.ts
Avec la lib leaflet-locatecontrol, pas réussi a la faire fonctionner malgré plusieurs tentatives.
Je pense que le code est bon.
Mais pas réussi a importé la lib.
Erreur : src/app/GN2CommonModule/map/geolocation/geolocation.component.ts(33,15): error TS2339: Property 'locate' does not exist on type 'typeof control'.

A mettre en lien avec https://github.com/domoritz/leaflet-locatecontrol/issues/191